version: '3.8'

services:
  web:
    image: codeigniter4_test
    build: .
    ports:
      - "80:80"
    volumes:
      - ./apache-vhost.conf:/etc/apache2/sites-available/000-default.conf
      # - ./.dockerConfig/start.sh:/start.sh
      # - ./var/www/html:/var/www/html
      # - ./.dockerConfig/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    environment:
      - VIRTUAL_HOST=localhost
    depends_on:
      - db

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: codeigniter
      MYSQL_USER: codeigniter
      MYSQL_PASSWORD: codeigniterpassword

volumes:
  db_data:
